syntax = 'All'
column_width = 120
line_endings = 'Unix'
indent_type = 'Tabs'
indent_width = 2
quote_style = "ForceSingle"
call_parentheses = "None"
collapse_simple_statement = "Never"
space_after_function_names = "Never"

[sort_requires]
enabled = false
